"use server";

export const getError = async () => {
  throw new Error("Ha ocurrido un error");
};
